<?php
require_once LAUCO_ROOT . '/inc/translations.php';
$locale = content_language_from_request();
$copy = [
'it'=>[
 'title'=>'Privacy Policy','subtitle'=>'Informazioni sul trattamento dei dati personali','intro'=>'Lauco Experience tratta i dati personali in relazione alle funzionalità del sito, ai moduli inviati dagli utenti, ai log tecnici degli accessi tramite QR e, solo previo consenso, alla misurazione statistica tramite Google Analytics.',
 'sections'=>[
  ['Titolare del trattamento','Il titolare del trattamento è il Gruppo Sportivo Monte Arvenis APS. Per richieste relative alla protezione dei dati puoi utilizzare i canali indicati nella pagina Contatti.'],
  ['Dati inviati tramite i moduli','I moduli del sito possono trattare nome, indirizzo email, eventuale telefono, contenuto del messaggio o della segnalazione, allegati e dati tecnici come indirizzo IP e user agent. I dati sono utilizzati per gestire la richiesta, la segnalazione o il contributo inviato.'],
  ['Volontariato e WhatsApp','Il modulo volontariato tratta nome, numero di telefono, eventuale email, zona, interessi e disponibilità per organizzare le attività territoriali. Con consenso esplicito, il numero è usato per inviare tramite WhatsApp l’invito al gruppo operativo e le comunicazioni collegate. Entrando in un gruppo WhatsApp, il numero e le informazioni del profilo WhatsApp diventano visibili agli altri partecipanti. I messaggi gestiti tramite il backoffice possono essere conservati per coordinare le attività e documentare le comunicazioni operative. Il consenso può essere revocato in qualsiasi momento.'],
  ['Newsletter','L’indirizzo email fornito per la newsletter è utilizzato per gestire l’iscrizione e l’invio delle comunicazioni richieste. Le preferenze e lo stato dell’iscrizione sono conservati nel sistema del sito.'],
  ['Google Analytics','Google Analytics 4 viene caricato soltanto dopo il consenso dell’utente. Senza consenso il tag Analytics non viene caricato. Il consenso può essere modificato o revocato in qualsiasi momento tramite “Gestisci cookie”. Quando attivo, Analytics può elaborare informazioni relative alla visita, al dispositivo e alla sessione secondo le impostazioni applicate dal sito. Le funzioni pubblicitarie restano disabilitate.'],
  ['Accessi tramite QR','Quando viene aperto l’URL /map presente sul QR fisico ufficiale, il server registra data e ora dell’accesso, user agent e una classificazione tecnica del dispositivo come mobile, tablet o desktop. L’indirizzo IP non viene conservato. Questi dati servono a distinguere e misurare l’utilizzo del QR fisico e a supportare verifiche tecniche. Il sistema QR non utilizza cookie analitici e non registra la geolocalizzazione del dispositivo.'],
  ['Accessi alle pagine e condivisioni','Per misurare i contenuti consultati e condivisi, il server incrementa conteggi aggregati per giorno, pagina, lingua e canale scelto dal pulsante Condividi. L’apertura del menu viene conteggiata separatamente dalle azioni di condivisione. Non vengono registrati indirizzo IP, user agent, cookie analitici o identificatori del visitatore e non vengono creati profili individuali.'],
  ['Base giuridica e conservazione','I dati dei moduli e i log tecnici QR sono trattati nell’ambito delle attività associative e di servizio collegate al progetto; Google Analytics è invece basato sul consenso. I dettagli dei log QR con data/ora, user agent e tipo dispositivo sono conservati per 90 giorni e poi eliminati automaticamente; i conteggi giornalieri aggregati possono essere conservati per finalità statistiche storiche. Gli altri dati sono conservati per il tempo necessario alle finalità per cui sono stati raccolti e agli eventuali obblighi applicabili.'],
  ['Destinatari e trasferimenti','I dati possono essere trattati da fornitori tecnici che supportano il funzionamento del sito. Quando Google Analytics è attivo, dati di utilizzo sono trattati anche tramite i servizi Google; Google dichiara che i propri prodotti Analytics possono comportare trasferimenti internazionali e descrive i relativi meccanismi di garanzia.'],
  ['Diritti','Nei casi previsti dalla normativa puoi chiedere accesso, rettifica, cancellazione, limitazione, opposizione e, ove applicabile, portabilità dei dati; puoi inoltre revocare il consenso senza pregiudicare la liceità del trattamento precedente alla revoca.'],
 ],
 'cookie'=>'Consulta la Cookie Policy','updated'=>'Ultimo aggiornamento: 16 agosto 2026',
],
'en'=>[
 'title'=>'Privacy Policy','subtitle'=>'Information on personal data processing','intro'=>'Lauco Experience processes personal data in connection with website functions, forms submitted by users, technical logs of accesses through the official QR code and, only after consent, statistical measurement through Google Analytics.',
 'sections'=>[
  ['Data controller','The data controller is Gruppo Sportivo Monte Arvenis APS. For data-protection requests, use the channels listed on the Contact page.'],
  ['Data submitted through forms','Website forms may process name, email address, optional telephone number, message or report content, attachments and technical data such as IP address and user agent. Data are used to manage the submitted request, report or contribution.'],
  ['Volunteering and WhatsApp','The volunteering form processes name, telephone number, optional email, area, interests and availability to organise local activities. With explicit consent, the number is used to send the operations-group invitation and related messages through WhatsApp. After joining a WhatsApp group, the number and WhatsApp profile information become visible to other members. Messages handled in the back office may be retained to coordinate activities and document operational communications. Consent may be withdrawn at any time.'],
  ['Newsletter','The email address provided for the newsletter is used to manage the subscription and send the requested communications. Subscription status and preferences are stored in the website system.'],
  ['Google Analytics','Google Analytics 4 is loaded only after user consent. Without consent the Analytics tag is not loaded. Consent can be changed or withdrawn at any time through “Manage cookies”. When active, Analytics may process information about the visit, device and session under the settings applied by the website. Advertising functions remain disabled.'],
  ['QR-code access','When the /map URL printed on the official physical QR code is opened, the server records the access date and time, user agent and a technical device classification such as mobile, tablet or desktop. The IP address is not retained. These data are used to distinguish and measure use of the physical QR code and to support technical checks. The QR system does not use analytics cookies and does not record device geolocation.'],
  ['Page views and sharing','To measure which content is viewed and shared, the server increments aggregate counts by day, page, language and the channel selected from the Share button. Opening the menu is counted separately from sharing actions. It does not record IP addresses, user agents, analytics cookies or visitor identifiers and does not create individual profiles.'],
  ['Legal basis and retention','Form data and technical QR logs are processed in connection with the association and service activities related to the project; Google Analytics is based on consent. Detailed QR logs containing date/time, user agent and device type are retained for 90 days and then deleted automatically, while aggregated daily counts may be retained for historical statistics. Other data are retained only as long as necessary for the purposes for which they were collected and for applicable obligations.'],
  ['Recipients and transfers','Data may be processed by technical providers supporting the website. When Google Analytics is active, usage data are also processed through Google services; Google states that Analytics products may involve international transfers and describes the safeguards it uses.'],
  ['Your rights','Where provided by law, you may request access, rectification, erasure, restriction, objection and, where applicable, portability. You may also withdraw consent without affecting processing carried out before withdrawal.'],
 ],
 'cookie'=>'Read the Cookie Policy','updated'=>'Last updated: 16 August 2026',
],
'de'=>[
 'title'=>'Datenschutz','subtitle'=>'Informationen zur Verarbeitung personenbezogener Daten','intro'=>'Lauco Experience verarbeitet personenbezogene Daten im Zusammenhang mit Website-Funktionen, von Nutzern übermittelten Formularen, technischen Protokollen der Zugriffe über den offiziellen QR-Code und – nur nach Einwilligung – der statistischen Messung mit Google Analytics.',
 'sections'=>[
  ['Verantwortlicher','Verantwortlicher für die Datenverarbeitung ist der Gruppo Sportivo Monte Arvenis APS. Für Datenschutzanfragen verwenden Sie die auf der Kontaktseite angegebenen Kanäle.'],
  ['Formulardaten','Formulare können Name, E-Mail-Adresse, optional Telefonnummer, Inhalt von Nachricht oder Meldung, Anhänge sowie technische Daten wie IP-Adresse und User Agent verarbeiten. Die Daten dienen der Bearbeitung der Anfrage, Meldung oder des Beitrags.'],
  ['Ehrenamt und WhatsApp','Das Ehrenamtsformular verarbeitet Name, Telefonnummer, optionale E-Mail, Gebiet, Interessen und Verfügbarkeit zur Organisation lokaler Aktivitäten. Mit ausdrücklicher Einwilligung wird die Nummer für die Einladung zur Einsatzgruppe und zugehörige WhatsApp-Mitteilungen verwendet. Nach dem Beitritt sind Nummer und WhatsApp-Profilinformationen für andere Gruppenmitglieder sichtbar. Im Backoffice bearbeitete Nachrichten können zur Koordination und Dokumentation operativer Mitteilungen gespeichert werden. Die Einwilligung kann jederzeit widerrufen werden.'],
  ['Newsletter','Die für den Newsletter angegebene E-Mail-Adresse wird zur Verwaltung der Anmeldung und zum Versand der angeforderten Mitteilungen verwendet. Status und Einstellungen der Anmeldung werden im System gespeichert.'],
  ['Google Analytics','Google Analytics 4 wird nur nach Einwilligung geladen. Ohne Einwilligung wird das Analytics-Tag nicht geladen. Die Einwilligung kann jederzeit über „Cookies verwalten“ geändert oder widerrufen werden. Werbefunktionen bleiben deaktiviert.'],
  ['QR-Zugriffe','Beim Öffnen der auf dem offiziellen physischen QR-Code angegebenen URL /map protokolliert der Server Datum und Uhrzeit des Zugriffs, den User Agent und eine technische Geräteklasse wie Mobilgerät, Tablet oder Desktop. Die IP-Adresse wird nicht gespeichert. Diese Daten dienen der Unterscheidung und Messung der Nutzung des physischen QR-Codes sowie technischen Prüfungen. Das QR-System verwendet keine Analytics-Cookies und speichert keine Geräte-Geolokalisierung.'],
  ['Seitenaufrufe und Teilen','Zur Messung aufgerufener und geteilter Inhalte erhöht der Server aggregierte Zähler nach Tag, Seite, Sprache und dem über die Teilen-Schaltfläche gewählten Kanal. Das Öffnen des Menüs wird getrennt von Teilen-Aktionen gezählt. IP-Adressen, User Agents, Analytics-Cookies oder Besucherkennungen werden nicht gespeichert und es werden keine individuellen Profile erstellt.'],
  ['Rechtsgrundlage und Speicherung','Formulardaten und technische QR-Protokolle werden im Zusammenhang mit den Vereins- und Dienstleistungsaktivitäten des Projekts verarbeitet; Google Analytics basiert auf Einwilligung. Detaillierte QR-Protokolle mit Datum/Uhrzeit, User Agent und Gerätetyp werden 90 Tage gespeichert und danach automatisch gelöscht; aggregierte Tageswerte können für historische Statistiken erhalten bleiben. Andere Daten werden nur so lange gespeichert, wie dies für die jeweiligen Zwecke und Pflichten erforderlich ist.'],
  ['Empfänger und Übermittlungen','Technische Dienstleister können Daten zur Unterstützung der Website verarbeiten. Bei aktivem Google Analytics werden Nutzungsdaten auch über Google-Dienste verarbeitet; Google weist darauf hin, dass Analytics-Produkte internationale Übermittlungen beinhalten können, und beschreibt entsprechende Garantien.'],
  ['Rechte','Soweit gesetzlich vorgesehen, bestehen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch und gegebenenfalls Datenübertragbarkeit. Eine Einwilligung kann jederzeit widerrufen werden.'],
 ],
 'cookie'=>'Cookie-Richtlinie lesen','updated'=>'Letzte Aktualisierung: 16. August 2026',
],
'sl'=>[
 'title'=>'Pravilnik o zasebnosti','subtitle'=>'Informacije o obdelavi osebnih podatkov','intro'=>'Lauco Experience obdeluje osebne podatke v povezavi s funkcijami spletnega mesta, obrazci uporabnikov, tehničnimi dnevniki dostopov prek uradne kode QR in – samo po soglasju – statističnim merjenjem prek Google Analytics.',
 'sections'=>[
  ['Upravljavec','Upravljavec osebnih podatkov je Gruppo Sportivo Monte Arvenis APS. Za zahteve v zvezi z varstvom podatkov uporabite kanale na strani Kontakt.'],
  ['Podatki iz obrazcev','Obrazci lahko obdelujejo ime, e-poštni naslov, neobvezno telefonsko številko, vsebino sporočila ali prijave, priloge ter tehnične podatke, kot sta IP-naslov in user agent. Podatki se uporabljajo za obravnavo poslane zahteve, prijave ali prispevka.'],
  ['Prostovoljstvo in WhatsApp','Obrazec za prostovoljstvo obdeluje ime, telefonsko številko, neobvezno e-pošto, območje, interese in razpoložljivost za organizacijo lokalnih dejavnosti. Z izrecnim soglasjem se številka uporablja za pošiljanje vabila v operativno skupino in povezanih sporočil prek WhatsAppa. Po vstopu so številka in podatki profila WhatsApp vidni drugim članom. Sporočila v zalednem sistemu se lahko hranijo za koordinacijo in dokumentiranje operativnih komunikacij. Soglasje lahko kadar koli prekličete.'],
  ['E-novice','E-poštni naslov za e-novice se uporablja za upravljanje prijave in pošiljanje zahtevanih obvestil. Stanje in nastavitve prijave se hranijo v sistemu spletnega mesta.'],
  ['Google Analytics','Google Analytics 4 se naloži samo po soglasju uporabnika. Brez soglasja se oznaka Analytics ne naloži. Soglasje lahko kadar koli spremenite ali prekličete z možnostjo »Upravljanje piškotkov«. Oglaševalske funkcije ostanejo izključene.'],
  ['Dostopi prek QR','Ko uporabnik odpre URL /map, natisnjen na uradni fizični kodi QR, strežnik zabeleži datum in čas dostopa, user agent ter tehnično razvrstitev naprave, kot so mobilna naprava, tablični ali namizni računalnik. IP-naslov se ne hrani. Podatki se uporabljajo za razlikovanje in merjenje uporabe fizične kode QR ter za tehnične preglede. Sistem QR ne uporablja analitičnih piškotkov in ne shranjuje geolokacije naprave.'],
  ['Ogledi in deljenje','Za merjenje ogledanih in deljenih vsebin strežnik poveča združene števce po dnevu, strani, jeziku in kanalu, izbranem z gumbom za deljenje. Odprtje menija se šteje ločeno od dejanj deljenja. Ne beleži naslovov IP, user agentov, analitičnih piškotkov ali identifikatorjev obiskovalcev in ne ustvarja individualnih profilov.'],
  ['Pravna podlaga in hramba','Podatki iz obrazcev in tehnični dnevniki QR se obdelujejo v povezavi z društvenimi in storitvenimi dejavnostmi projekta; Google Analytics temelji na soglasju. Podrobni dnevniki QR z datumom/časom, user agentom in vrsto naprave se hranijo 90 dni in nato samodejno izbrišejo, združeni dnevni seštevki pa se lahko hranijo za zgodovinsko statistiko. Drugi podatki se hranijo le toliko časa, kolikor je potrebno za namen in veljavne obveznosti.'],
  ['Prejemniki in prenosi','Podatke lahko obdelujejo tehnični ponudniki, ki podpirajo delovanje spletnega mesta. Ko je Google Analytics aktiven, se podatki o uporabi obdelujejo tudi prek Googlovih storitev; Google navaja, da lahko izdelki Analytics vključujejo mednarodne prenose in opisuje uporabljena jamstva.'],
  ['Pravice','Kjer zakon to določa, lahko zahtevate dostop, popravek, izbris, omejitev, ugovor in po potrebi prenosljivost. Soglasje lahko kadar koli prekličete.'],
 ],
 'cookie'=>'Preberite pravilnik o piškotkih','updated'=>'Zadnja posodobitev: 16. avgust 2026',
],
];
$c=$copy[$locale] ?? $copy['it'];
?>
<!DOCTYPE html><html lang="<?= htmlspecialchars($locale, ENT_QUOTES, 'UTF-8') ?>"><head><?php require LAUCO_VIEW_PATH . '/partials/header.php'; ?>
<style>.policy-page .lead{font-size:18px;line-height:1.75;color:#555}.policy-card{background:#fff;padding:28px;margin:0 0 22px;box-shadow:0 10px 30px rgba(0,0,0,.06)}.policy-card h3{margin-top:0}.policy-card p{color:#666;line-height:1.75}.policy-note{font-size:13px;color:#777;margin-top:30px}</style></head><body>
<div id="myloader"><span class="loader"><div class="inner-loader"></div></span></div><div id="main-wrap" class="full-width"><?php require LAUCO_VIEW_PATH . '/partials/menu.php'; ?>
<div id="page-content" class="header-static"><div id="flexslider" class="fullpage-wrap small"><ul class="slides"><li style="background-image:url(assets/img/contact.jpg)"><div class="container text text-center"><h1 class="white margin-bottom-small"><?= htmlspecialchars($c['title'], ENT_QUOTES, 'UTF-8') ?></h1><p class="heading white"><?= htmlspecialchars($c['subtitle'], ENT_QUOTES, 'UTF-8') ?></p></div><div class="gradient dark"></div></li></ul></div>
<div id="page-wrap" class="content-section fullpage-wrap policy-page"><div class="container text"><p class="lead"><?= htmlspecialchars($c['intro'], ENT_QUOTES, 'UTF-8') ?></p>
<?php foreach ($c['sections'] as [$heading,$text]): ?><section class="policy-card"><h3><?= htmlspecialchars($heading, ENT_QUOTES, 'UTF-8') ?></h3><p><?= htmlspecialchars($text, ENT_QUOTES, 'UTF-8') ?></p></section><?php endforeach; ?>
<p><a class="btn-alt small" href="<?= htmlspecialchars(content_language_url($locale, '/cookie'), ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($c['cookie'], ENT_QUOTES, 'UTF-8') ?></a></p><p class="policy-note"><?= htmlspecialchars($c['updated'], ENT_QUOTES, 'UTF-8') ?></p></div></div></div>
<?php require LAUCO_VIEW_PATH . '/partials/footer.php'; ?></div><?php require LAUCO_VIEW_PATH . '/partials/scripts.php'; ?></body></html>
